### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by burlakabogdan** [mtcextendee/mautic-fast-contact-update-bundle#1]
welcome. I tried to install the plugin according to the instructions:

> unzip files to plugins / MauticFastContactBundle
> Go to / s / plugins / reload
  
but show 

> 0 plug-ins have been shown

it was necessary to change the name MauticFastContactBundle to MauticFastContactUpdateBundle

it worked for me.

**Comment by kuzmany** [comment]
Yes, It was typo mistake.
I fixed it.
Thanks
